# Optional metadata for dashboard (setup_zones.py does not touch this file)
# You can change zones/names without redrawing polygons.
- id: 1
  name: B7
  zone: B
  preset: 1
- id: 2
  name: B60
  zone: B
  preset: 1
- id: 3
  name: B18
  zone: B
  preset: 1
- id: 4
  name: B48
  zone: B
  preset: 2
- id: 5
  name: B27
  zone: B
  preset: 2
- id: 6
  name: B10
  zone: B
  preset: 2
- id: 7
  name: B22
  zone: B
  preset: 3
- id: 8
  name: B26
  zone: B
  preset: 3
- id: 9
  name: B34
  zone: B
  preset: 3
- id: 10
  name: B49
  zone: B
  preset: 4
- id: 11
  name: B19
  zone: B
  preset: 4
- id: 12
  name: B16
  zone: B
  preset: 4
- id: 13
  name: B31
  zone: B
  preset: 5
- id: 14
  name: B17
  zone: B
  preset: 5
- id: 15
  name: B44
  zone: B
  preset: 6
- id: 16
  name: B24
  zone: B
  preset: 6
- id: 17
  name: B56
  zone: B
  preset: 7
- id: 18
  name: B13
  zone: B
  preset: 7
- id: 19
  name: B40
  zone: B
  preset: 8
- id: 20
  name: B47
  zone: B
  preset: 9
- id: 21
  name: B23
  zone: B
  preset: 9
- id: 22
  name: B36
  zone: B
  preset: 10
- id: 23
  name: B54
  zone: B
  preset: 10
- id: 24
  name: B41
  zone: B
  preset: 10
- id: 25
  name: B37
  zone: B
  preset: 11
- id: 26
  name: B58
  zone: B
  preset: 11
- id: 27
  name: B29
  zone: B
  preset: 11
- id: 28
  name: B52
  zone: B
  preset: 12
- id: 29
  name: B25
  zone: B
  preset: 12
- id: 30
  name: B53
  zone: B
  preset: 12
- id: 31
  name: B14
  zone: B
  preset: 13
- id: 32
  name: B12
  zone: B
  preset: 13
- id: 33
  name: B59
  zone: B
  preset: 13
- id: 34
  name: B39
  zone: B
  preset: 13
- id: 35
  name: B55
  zone: B
  preset: 14
- id: 36
  name: B35
  zone: B
  preset: 14
- id: 37
  name: B15
  zone: B
  preset: 14
- id: 38
  name: B46
  zone: B
  preset: 14
- id: 39
  name: B38
  zone: B
  preset: 14
- id: 40
  name: B8
  zone: B
  preset: 15
- id: 41
  name: B30
  zone: B
  preset: 15
- id: 42
  name: B57
  zone: B
  preset: 15
- id: 43
  name: B45
  zone: B
  preset: 15
- id: 44
  name: B43
  zone: B
  preset: 16
- id: 45
  name: B42
  zone: B
  preset: 16
- id: 46
  name: B21
  zone: B
  preset: 16
- id: 47
  name: B50
  zone: B
  preset: 17
- id: 48
  name: B9
  zone: B
  preset: 17

